namespace NatureRecorder.Interpreter.Entities
{
    public enum CommandType
    {
        help,
        add,
        addcategory,
        addlocation,
        addsighting,
        addspecies,
        adduser,
        categories,
        check,
        connection,
        delete,
        deleteuser,
        edit,
        exit,
        export,
        import,
        interactive,
        list,
        locations,
        move,
        rename,
        report,
        setpassword,
        species,
        summary,
        update
    }
}
