namespace NatureRecorder.Interpreter.Entities
{
    public enum CommandType
    {
        help,
        add,
        categories,
        check,
        connection,
        delete,
        deleteuser,
        edit,
        exit,
        export,
        history,
        import,
        interactive,
        list,
        locations,
        move,
        rename,
        report,
        settings,
        setpassword,
        species,
        summary,
        update
    }
}
